version: 2.1

orbs:
  cloudflare-wrangler: coryzibell/cloudflare-wrangler@volatile

workflows:

  deploy-cloudflare-production:
    jobs:
      - whoami:
          docker:
            - image: cimg/base:stable
          steps:
            - run:
                name: whoami
                command: whoami

      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-thistakesmeback-com
          filters:
            branches:
              only:
                - master
